url: "https://nanobytesecurity.com"
site-css:
  - "/assets/css/nanobyte-header.css"
  - "/assets/css/nanobyte.css"

# ---------- SHARED HEADER / FOOTER (keep identical on both sites) ----------
title: Nanobyte Security
url: "https://blog.nanobytesecurity.com"
url-pretty: "NanobyteSecurity.com"

site-css:
  - "/assets/css/nanobyte-header.css"
  - "/assets/css/nanobyte.css"

social-network-links:
  email: "alex@nanobytesecurity.com"
  linkedin: alexander-dalzell

remove-ads: true
footer-hide-themename: true
# ---------------------------------------------------------------------------
